### ISSUE TITLE
Bookmark-Page Button

### ISSUE THREAD

**Issue by DanielWahl** [colorcube/bookmark_pages#4] opened 2019-06-27 13:13 UTC
Hello,

I'm using your extensions for an intranet site.
I have problem to add the "Bookmark-page"-Button into the fluid-Template.
When I use the code given in the documentation, I get an error message: 

> Oops, an error occurred! Code: 20190627150334a679de71

```
<a class="bookmark-ajax-submit bookmark-this-page"
data-ajaxuri="{t:uri.ajaxAction(extensionName: 'bookmarkpages', pluginName: 'Bookmarks', controller: 'Bookmarks', action: 'bookmark', contextRecord: 'currentPage')}"
>bookmark page</a>
```

I'm running Typo3 8.7.26 with RealURL.

I don't know if this is a problem with the whole Extension, or just with this ajax a-tag?

Thanks in advance,
Daniel

**Comment by colorcube** [comment] 2019-06-27 21:13
You have to enable error display to see the reason for the error. It's impossible to say what's the problem is without more details. Maybe it's not even related to the bookmarks extension.

https://www.google.com/search?q=typo3+8.7+enable+error+display

**Comment by DanielWahl** [comment] 2019-06-27 21:29
The error display says, that the namespace "t" from {t:uri.ajaxAction....} does not exist,

> Fluid parse error in template partial_header_1cf805f04e08b379c10aa7f1ec6a6882dcfcbdbc, line 1 at character 1. Error: Unknown Namespace: t (error code 0). Template source chunk: </div>

**Comment by colorcube** [comment] 2019-06-27 22:18
You have to add the namespace in your fluid template for the extension TyposcriptRendering:

`xmlns:t="http://typo3.org/ns/Helhum/TyposcriptRendering/ViewHelpers"`

so the beginning of your Template might look like this:

```
<html xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
	  xmlns:t="http://typo3.org/ns/Helhum/TyposcriptRendering/ViewHelpers">
```

This is not part of the bookmarks extension. TyposcriptRendering is used to make the ajax call.

**Comment by DanielWahl** [comment] 2019-06-27 22:28
Thanks for your help and quick response.

This works :). I didn't know that your extension uses the TyposcriptRendering-Extension.

But the Buttons is still responseless. I'm logged-in in FE, and clicking the "bookmark page" Button isn't working.

Rendered output in the debugger:
`<a class="bookmark-ajax-submit bookmark-this-page" data-ajaxuri="/index.php?id=2&amp;tx_typoscriptrendering%5Bcontext%5D=%7B%22record%22%3A%22pages_2%22%2C%22path%22%3A%22tt_content.list.20.bookmarkpages_bookmarks%22%7D&amp;tx_bookmarkpages_bookmarks%5Baction%5D=bookmark&amp;tx_bookmarkpages_bookmarks%5Bcontroller%5D=Bookmarks&amp;cHash=6f571a1866fb36c079b792ab22af68c3"> bookmark page </a>`

May there be a wrong parameter?

**Comment by colorcube** [comment] 2019-06-28 06:29
The ajax url looks right.

The extension itself don't uses the TyposcriptRendering-Extension. The described example uses it. Nevertheless that is not clearly descrbed.

The button is not really part of the extension, it's a simple example how that cold be done. The button just trigger the bookmarking, there's no visible functionality. The javascript add the class `is-bookmarked` to the button.

When the button works, the button should have the class added and the bookmark list should display the bookmark after reload.

Here's a checklist

- make shure to include the TypoScript of the extension (adapt it to your needs)
- make shure to include the extension javascript
- make shure jquery in included
- look for javascript errors on page load
- look for javascript errors on clicking the bookmark button
- test if the ajax request is sent and if an response is sent

This is a bit out of scope of this bugtracker ...

**Comment by DanielWahl** [comment] 2019-06-28 14:02
I have now figured out what the problem was.
The typoscript_rendering extension has a bug as mentioned here: [https://github.com/helhum/typoscript_rendering/issues/60](url)

Because of this bug, the ajax Call with t:uri.ajaxAction wasn't possible.
Fixing the bug like in the issue from ts_rendering fixed the problem with your bookmark extension.

**Comment by colorcube** [comment] 2019-07-01 07:32
Thanks for the info!

**Closed as completed by colorcube** 2019-07-01 07:32 UTC
